name: {{cookiecutter.env_name}}
dependencies:
    - python>=3.8
    - pytest
    - pip
    - pip:
        - -e .
        - click
        - Sphinx
        - coverage
        - awscli
        - flake8
        - python-dotenv>=0.5.1